core/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('watch.urls')),
]

watch/urls.py
from django.urls import path

from watch.views import (
    EventCreateView,
    EventDetailView,
    EventListView,
    EventStatsView,
    EventUpdateView,
    delete_speaker,
    event_json,
    start_speaker,
    stop_speaker,
    update_speaker,
)

app_name = "watch"

urlpatterns = [
    path("", EventListView.as_view(), name="event_list"),
    path("create/", EventCreateView.as_view(), name="event_create"),
    path("start/", start_speaker, name="start_speaker"),
    path("stop/", stop_speaker, name="stop_speaker"),
    path("<uuid:pk>/speaker/update/", update_speaker, name="speaker_update"),
    path("<uuid:pk>/speaker/delete/", delete_speaker, name="speaker_delete"),
    path("<uuid:pk>/update/", EventUpdateView.as_view(), name="event_update"),
    path("<uuid:pk>/stats/", EventStatsView.as_view(), name="event_stats"),
    path("<uuid:pk>/data/", event_json, name="event_data"),
    path("<uuid:pk>/", EventDetailView.as_view(), name="event_detail"),
]

watch/models.py
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils.models import TimeStampedModel, UUIDModel

channel_layer = get_channel_layer()


def default_genders():
    return [x.strip() for x in getattr(settings, 'DEFAULT_GENDERS', 'm, f, o').split(',')]


def default_languages():
    return [x.strip() for x in getattr(settings, 'DEFAULT_LANGUAGES', 'de,fr,it').split(',')]


def default_positions():
    return [x.strip() for x in getattr(settings, 'DEFAULT_POSITIONS', 'GL,Basis').split(',')]


class Event(TimeStampedModel, UUIDModel):
    name = models.CharField(max_length=255)
    owner = models.ForeignKey(get_user_model(), models.CASCADE)
    genders = models.JSONField(default=default_genders)
    languages = models.JSONField(default=default_languages)

    points = models.TextField(blank=True)
    positions = models.JSONField(default=default_positions)

    def send_update(self):
        print(f'event_{self.id.hex}')
        async_to_sync(channel_layer.group_send)(f'event_{self.id.hex}', {"type": "event.update"})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.send_update()

    class Meta:
        ordering = ['-created']


class Speaker(models.Model):
    start = models.DateTimeField(verbose_name=_("start"), auto_now_add=True)
    end = models.DateTimeField(verbose_name=_("end"), null=True, blank=True)

    event = models.ForeignKey(Event, models.CASCADE)

    gender = models.CharField(max_length=50, blank=True)
    language = models.CharField(max_length=4, blank=True)
    position = models.CharField(max_length=60, blank=True)
    point = models.CharField(max_length=255, blank=True)

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        print("Update")
        self.event.send_update()

    class Meta:
        ordering = ['-start']

watch/forms.py
from django import forms
from django.forms.widgets import TextInput

from watch.models import Event


class EventForm(forms.ModelForm):
    class Meta:
        model = Event
        fields = ["name", "genders", "languages", "positions", "points"]

        widgets = {
            "genders": TextInput,
            "languages": TextInput,
            "positions": TextInput,
        }

watch/views.py
import uuid

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http.response import HttpResponseBadRequest, JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.translation import gettext as _
from django.views.decorators.http import require_POST
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView

from watch.forms import EventForm
from watch.models import Event, Speaker
from watch.services import (
    event_as_dict,
    has_active_speaker,
    read_fields,
    speakers_as_dict,
    update_end_time,
)

# Create your views here.


class EventListView(LoginRequiredMixin, ListView):
    model = Event

    def get_queryset(self):
        return super().get_queryset().filter(owner=self.request.user)


class EventCreateView(LoginRequiredMixin, CreateView):
    model = Event
    form_class = EventForm

    success_url = reverse_lazy("watch:event_list")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(CreateView, self).form_valid(form)


class EventUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Event
    form_class = EventForm
    success_url = reverse_lazy("watch:event_list")

    def test_func(self):
        return self.get_object().owner == self.request.user


@require_POST
def start_speaker(request):
    pk = request.POST.get("pk", None) or uuid.UUID(int=0)

    event = get_object_or_404(Event, pk=pk)

    if event.speaker_set.filter(end__isnull=True).exists():
        return HttpResponseBadRequest(_("already started a speaker"))

    speaker = Speaker.objects.create(event=event)

    return JsonResponse(
        {
            "id": speaker.id,
        }
    )


@require_POST
def stop_speaker(request):
    pk = request.POST.get("pk", None) or uuid.UUID(int=0)

    event = get_object_or_404(Event, pk=pk)

    speaker = event.speaker_set.filter(end__isnull=True).first()

    if speaker is None:
        return HttpResponseBadRequest(_("no speaker is open"))

    speaker.end = timezone.now()
    speaker.save()

    return JsonResponse(
        {
            "id": speaker.id,
        }
    )


@require_POST
def update_speaker(request, pk):
    event = get_object_or_404(Event, pk=pk)

    speaker_pk = request.POST.get("pk", None)

    event.speaker_set.filter(pk=speaker_pk).update(
        **read_fields(request.POST, "gender", "language", "point", "position")
    )
    if end := request.POST.get("end"):
        update_end_time(event.speaker_set.filter(pk=speaker_pk).first(), end)

    event.send_update()

    return JsonResponse({"id": speaker_pk})


def delete_speaker(request, pk):
    event = get_object_or_404(Event, pk=pk)

    speaker_pk = request.POST.get("pk", None)
    event.speaker_set.filter(pk=speaker_pk).delete()

    event.send_update()

    return JsonResponse({"id": speaker_pk})


def event_json(request, pk):
    event = get_object_or_404(Event, pk=pk)

    return JsonResponse(
        {
            "speakers": speakers_as_dict(event),
            "isOpen": has_active_speaker(event),
        }
    )


class EventDetailView(DetailView):
    model = Event

    def get_context_data(self, **kwargs):
        data = super().get_context_data(**kwargs)
        data["eventDict"] = event_as_dict(data["event"])
        return data


class EventStatsView(LoginRequiredMixin, UserPassesTestMixin, EventDetailView):
    template_name = "watch/event_stats.html"

    def test_func(self):
        return self.get_object().owner == self.request.user

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="de">
  <head>
    <title>{% block head_title %}{% endblock head_title %} | Language Watch</title>
    <link href="{% static 'normalize.css' %}"  rel="stylesheet"/>
    <link href="{% static 'watch/style.css' %}"  rel="stylesheet"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <meta name="description" content="Tool to watch language"/>
    <meta name="keywords" content="language watch" />
    {% block extra_head %}
    {% endblock extra_head %}
  </head>
  <body>
    {% block body %}

      <header>
        <a class="brand" href="{% url 'watch:event_list' %}">Language-Watch</a>
        <nav>
          <a href="{% url 'watch:event_list' %}">{% trans "Events" %}</a>
          {% if user.is_authenticated %}
            <a href="{% url 'account_email' %}">{% trans "Change E-mail" %}</a>
            <a href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
          {% else %}
            <a href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
            <a href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
          {% endif %}
        </nav>
      </header>

      <div class="messages">
        {% for message in messages %}
          <div class="message" onclick="remove(this)">
            {{ message }}
          </div>
        {% endfor %}
      </div>

      <main>
        {% block content %}
        {% endblock content %}
      </main>
    {% endblock body %}
    {% block extra_body %}
    {% endblock extra_body %}
    <script>
      function remove(element) {
        element.remove();
      }
    </script>
  </body>
</html>

templates/watch/event_detail.html
{% extends "base.html" %}
{% load static %}

{% block head_title %}{{ event.name }}{% endblock head_title %}

{% block content %}

  {{ eventDict|json_script:"event-data" }}

  <div id="app" data-id="{{ event.id }}">
    <div class="actionRow">
      <button class="action" id="stop" @click="stop" v-if="isOpen">Stop</button>
      <button class="action" id="start" @click="start" v-else>Start</button>
      <span>${countRequests} {% trans "requests" %} </span>
      <span>${totalDuration}</span>
    </div>

    <div class="forms">
      <form v-for="speaker in speakers" v-bind:id="'form_' + speaker.id">
      </form>
    </div>

    <table>
      <thead>
        <tr>
          <th class="number">
            {% trans 'Start' %}
          </th>
          <th class="number">
            {% trans 'End' %}
          </th>
          <th class="number">
            {% trans 'Duration' %}
          </th>
          <th>
            {% trans 'Gender' %}
          </th>
          <th>
            {% trans 'Language' %}
          </th>
          <th>
            {% trans 'Position' %}
          </th>
          <th>
            {% trans 'Point' %}
          </th>
          <th>
            {% trans 'Action' %}
          </th>
        </tr>
      </thead>
      <tbody>
        <tr v-for="speaker in speakers">
          <input type="hidden" name="pk" v-bind:value="speaker.id" v-bind:form="'form_' + speaker.id"/>
          <td class="number">
            ${speaker.start}
          </td>
          <td class="number">
            <input name="end" @input="onSpeakerChange(speaker.id)" v-bind:form="'form_' + speaker.id" type="time" :value="speaker.end"/>
          </td>
          <td class="number">
            ${
            String(Math.floor(speaker.duration / 60)).padStart(2, "0")
            }:${String(Math.floor(speaker.duration % 60)).padStart(2, "0")}
          </td>
          <td>
            <select @change="onSpeakerChange(speaker.id)" name="gender" v-bind:form="'form_' + speaker.id">
              <option
                v-bind:selected="gender == speaker.gender"
                v-for="gender in genders"
                v-bind:value="gender"
              >
                ${gender}
              </option>
            </select>
          </td>
          <td>
            <select @change="onSpeakerChange(speaker.id)" name="language" v-bind:form="'form_' + speaker.id">
              <option
                v-bind:selected="language==speaker.language"
                v-for="language in languages"
                v-bind:value="language"
              >
                ${language}
              </option>
            </select>
          </td>
          <td>
            <select @change="onSpeakerChange(speaker.id)" name="position" v-bind:form="'form_' + speaker.id">
              <option
                v-bind:selected="position==speaker.position"
                v-for="position in positions"
                v-bind:value="position"
              >
                ${position}
              </option>
            </select>
          </td>
          <td>
            <select @change="onSpeakerChange(speaker.id)" name="point" v-bind:form="'form_' + speaker.id">
              <option
                v-bind:selected="point == speaker.point"
                v-for="point in points"
                v-bind:value="point"
              >
                ${point}
              </option>
            </select>
          </td>
          <td class="deleteCell">
            <form @submit="deleteSpeaker">
              <input type="hidden" v-bind:value="speaker.id" name="pk" />
              <button v-if="speaker.id != wantDeletion" @click="initiateDelete(speaker.id)" type="button">{% trans "Delete" %}</button>
              <button v-if="speaker.id == wantDeletion" class="cancel" type="button" @click="cancelDelete">{% trans "Cancel" %}</button>
              <button v-if="speaker.id == wantDeletion" class="delete" type="submit">{% trans "Are your sure?" %}</button>
            </form>
          </td>
        </tr>
      </tbody>
    </table>
  </div>

  {% csrf_token %}
  <script src="{% static 'watch/event_detail.js' %}" type="module"></script>
{% endblock content %}

templates/watch/event_form.html
{% extends "base.html" %}

{% block head_title %}

  {% if object %}
    {{ object.name }}
  {% else %}
    {% trans 'Create Event' %}
  {% endif %}
{% endblock head_title %}

{% block content %}
  <div class="title">
    {% if object %}
      <h2>{{ object.name }}</h2>
    {% else %}
      <h2>{% trans 'Create Event' %}</h2>
    {% endif %}
    <a class="button empty" href="{% url 'watch:event_list' %}">{% trans 'Back' %}</a>
  </div>
  <form class="form" method="post" action="">
    {{ form }}
    {% csrf_token %}
    <div class="buttons">
      <button type="submit">{% trans 'Submit' %}</button>
      <a class="button empty" href="{% url 'watch:event_list' %}">{% trans 'Back' %}</a>
    </div>
  </form>
{% endblock content %}

templates/watch/event_list.html
{% extends "base.html" %}

{% block head_title %} {% trans "Events" %} {% endblock head_title %}

{% block content %}
  <div class="title">
    <h2>{% trans 'Events' %}</h2>
    <a class="button" href="{% url "watch:event_create" %}">{% trans 'create event' %}</a>
  </div>

  <div class="events">
    {% for event in event_list %}
      <span>
        {{ event.name }}
      </span>
      <div class="buttons">
        <a class="button" href="{% url "watch:event_update" event.pk %}">
          {% trans "Update" %}
        </a>
        <a class="button" href="{% url 'watch:event_detail' event.pk %}">
          {% trans "Record time" %}
        </a>
        <a class="button" href="{% url 'watch:event_stats' event.pk %}">
          {% trans "Charts" %}
        </a>
      </div>
    {% endfor %}
  </div>
{% endblock content %}

templates/watch/event_stats.html
{% extends "base.html" %}
{% load static %}

{% block head_title %}{{ event.name }}{% endblock head_title %}

{% block content %}

  {{ eventDict|json_script:"event-data" }}

  <div id="app" data-id="{{ event.id }}">
    <section class="pieChart chart">
      <div id="pieChartDiv" class="plot"></div>
      <form id="pieChartForm" @change="drawPieChart" class="chartForm">
        <div class="kind">
          <div class="checkbox">
            <label for="enable_duration">Duration</label>
            <input type="checkbox" id="enable_duration" name="durationEnabled" />
          </div>
        </div>
        <div id="groupers" class="formGroup">
          <h2>Groupers</h2>
          <div class="checkbox">
            <label for="grouper_gender">Gender</label>
            <input type="checkbox" id="grouper_gender" name="groupers" value="gender"/>
          </div>
          <div class="checkbox">
            <label for="grouper_language">Language</label>
            <input type="checkbox" id="grouper_language" name="groupers" value="language"/>
          </div>
          <div class="checkbox">
            <label for="grouper_position">Position</label>
            <input type="checkbox" id="grouper_position" name="groupers" value="position"/>
          </div>
          <div class="checkbox">
            <label for="grouper_point">Point</label>
            <input type="checkbox" id="grouper_point" name="groupers" value="point"/>
          </div>
        </div>
        <div id="filters" class="formGroup">
          <h2>Filter</h2>
          <div class="filter" v-for="it in [['gender', genders], ['language', languages], ['position', positions], ['point', points]]">
            <label :for="'filter_' + it[0]">${it[0]}</label>
            <select :id="'filter_' + it[0]" :name="'filter_' + it[0]">
              <option v-for="value in it[1]" :value="value">${value}</option>
            </select>
          </div>
        </div>
      </form>
    </section>
    <section class="barChart chart">
      <div id="barChartDiv" class="plot">
      </div>
      <form id="barChartForm" @change="drawBarChart">
        <div class="stacked">
            <label for="enable_stacked">Stacked</label>
            <input type="checkbox" id="enable_stacked" name="durationEnabled" />
        </div>
      </form>
    </section>
  </div>

  {% csrf_token %}
  <script src="https://cdn.plot.ly/plotly-2.9.0.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/danfojs@1.0.2/lib/bundle.min.js"></script>
  <script type="module" src="{% static 'watch/event_stats.js' %}"></script>
{% endblock content %}